#define DEBUG
#undef DEBUG

//Generated by GPT-5.3-Codex 

#include "constantPropagation.hh"
#include "MinusIntConverter.hh"

using namespace std;
using namespace fdmj;

namespace {

class ConstantPropagationVisitor : public ASTVisitor {
public:
	AST *newNode = nullptr;

	explicit ConstantPropagationVisitor(AST *n) : newNode(n) {}

	void visit(Program *node) override {
		if (node == nullptr) {
			newNode = nullptr;
			return;
		}
		MainMethod *m = nullptr;
		if (node->main != nullptr) {
			node->main->accept(*this);
			m = static_cast<MainMethod *>(newNode);
		}
		newNode = new Program(node->getPos()->clone(), m);
	}

	void visit(MainMethod *node) override {
		if (node == nullptr) {
			newNode = nullptr;
			return;
		}
		vector<Stm *> *sl = nullptr;
		if (node->sl != nullptr) {
			sl = new vector<Stm *>();
			for (Stm *s : *node->sl) {
				if (s == nullptr)
					continue;
				s->accept(*this);
				if (newNode != nullptr)
					sl->push_back(static_cast<Stm *>(newNode));
			}
			if (sl->empty()) {
				delete sl;
				sl = nullptr;
			}
		}
		newNode = new MainMethod(node->getPos()->clone(), sl);
	}

	void visit(Assign *node) override {
		if (node == nullptr || node->left == nullptr || node->exp == nullptr) {
			newNode = nullptr;
			return;
		}
		node->left->accept(*this);
		Exp *l = static_cast<Exp *>(newNode);
		node->exp->accept(*this);
		Exp *r = static_cast<Exp *>(newNode);
		newNode = new Assign(node->getPos()->clone(), l, r);
	}

	void visit(Return *node) override {
		if (node == nullptr || node->exp == nullptr) {
			newNode = nullptr;
			return;
		}
		node->exp->accept(*this);
		Exp *e = static_cast<Exp *>(newNode);
		newNode = new Return(node->getPos()->clone(), e);
	}

	void visit(BinaryOp *node) override {
		if (node == nullptr || node->left == nullptr || node->right == nullptr ||
				node->op == nullptr) {
			newNode = nullptr;
			return;
		}

		// Bottom-up: fold children first, then try to fold current node.
		node->left->accept(*this);
		Exp *l = static_cast<Exp *>(newNode);
		node->right->accept(*this);
		Exp *r = static_cast<Exp *>(newNode);

		if (l != nullptr && r != nullptr && l->getASTKind() == ASTKind::IntExp &&
				r->getASTKind() == ASTKind::IntExp) {
			const int lv = static_cast<IntExp *>(l)->val;
			const int rv = static_cast<IntExp *>(r)->val;
			const string &op = node->op->op;

			if (op == "+") {
				newNode = new IntExp(node->getPos()->clone(), lv + rv);
				return;
			}
			if (op == "-") {
				newNode = new IntExp(node->getPos()->clone(), lv - rv);
				return;
			}
			if (op == "*") {
				newNode = new IntExp(node->getPos()->clone(), lv * rv);
				return;
			}
			if (op == "/") {
				// Keep expression if dividing by zero to preserve runtime behavior.
				if (rv != 0) {
					newNode = new IntExp(node->getPos()->clone(), lv / rv);
					return;
				}
			}
		}

		newNode = new BinaryOp(node->getPos()->clone(), l, node->op->clone(), r);
	}

	void visit(UnaryOp *node) override {
		if (node == nullptr || node->exp == nullptr || node->op == nullptr) {
			newNode = nullptr;
			return;
		}
		node->exp->accept(*this);
		Exp *e = static_cast<Exp *>(newNode);
		newNode = new UnaryOp(node->getPos()->clone(), node->op->clone(), e);
	}

	void visit(IdExp *node) override {
		newNode = (node == nullptr) ? nullptr : static_cast<IdExp *>(node->clone());
	}

	void visit(OpExp *node) override {
		newNode = (node == nullptr) ? nullptr : static_cast<OpExp *>(node->clone());
	}

	void visit(IntExp *node) override {
		newNode = (node == nullptr) ? nullptr : static_cast<IntExp *>(node->clone());
	}
};

} // namespace

using namespace std;
using namespace fdmj;

Program *constantPropagate(Program *root) {
	if (root == nullptr)
		return nullptr;

	Program *rewritten = minusIntRewrite(root);
	ConstantPropagationVisitor v(nullptr);
	rewritten->accept(v);
	return static_cast<Program *>(v.newNode);
}
