#define DEBUG
#undef DEBUG

//generated by GPT-5.3-codex

#include <iostream>
#include <cstdlib>
#include <variant>
#include <map>
#include <vector>
#include <algorithm>
#include "ASTheader.hh"
#include "FDMJAST.hh"
#include "namemaps.hh"

using namespace std;
using namespace fdmj;

namespace {

constexpr const char* kMainClassName = "__main__";
constexpr const char* kMainMethodName = "main";
constexpr const char* kReturnFormalName = "__return__";

[[noreturn]] void fail_with_msg(const string& msg, AST* node = nullptr) {
    if (node != nullptr && node->getPos() != nullptr) {
        cerr << "at position: " << node->getPos()->print() << endl;
    }
    cerr << "Error: " << msg << endl;
    exit(1);
}

Formal* make_return_formal(AST* owner, Type* return_type) {
    Pos* pos = nullptr;
    if (owner != nullptr && owner->getPos() != nullptr) {
        pos = owner->getPos()->clone();
    } else {
        pos = new Pos(0, 0, 0, 0);
    }
    IdExp* ret_id = new IdExp(pos->clone(), kReturnFormalName);
    return new Formal(pos, return_type, ret_id);
}

bool check_immutable(string classname)
{
    // cout<<"check_immutable "+classname<<endl;
    if(classname.length()<10) return false;
    const string _immutable="_Immutable";
    for(int i=1;i<=10;i++)
    {
        if(classname[classname.length()-i]!=_immutable[10-i]) return false;
    }
    return true;
}

} // namespace

void AST_Name_Map_Visitor::visit(Program* node) {
#ifdef DEBUG
    std::cout << "Visiting Program" << std::endl;
#endif
    if (node == nullptr) {
         return;
    }

    // Pre-register all class names so extends relations work even if parent is declared later.
    if (node->cdl != nullptr) {
        for (auto cl : *(node->cdl)) {
            if (cl == nullptr || cl->id == nullptr) {
                continue;
            }
            if (!name_maps->add_class(cl->id->id)) {
                fail_with_msg("duplicate class declaration: " + cl->id->id, cl);
            }
        }
    }

    if (node->main != nullptr) {
        node->main->accept(*this);
    }
    if (node->cdl != nullptr) {
        for (auto cl : *(node->cdl)) {
            cl->accept(*this);
        }
    }
}

//rest of the visit functions here, you need to complete the code!
void AST_Name_Map_Visitor::visit(ClassDecl* node) {
    if (node == nullptr || node->id == nullptr) {
        return;
    }
    current_visiting_class = node->id->id;

    if (node->eid != nullptr) {
        if (!name_maps->is_class(node->eid->id)) {
            fail_with_msg("parent class not declared: " + node->eid->id, node->eid);
        }
        if (!name_maps->add_class_hiearchy(current_visiting_class, node->eid->id)) {
            fail_with_msg("invalid class hierarchy for class: " + current_visiting_class, node);
        }
    }
    if (check_immutable(current_visiting_class))
    {
        if(!name_maps->set_class_immutable(current_visiting_class,true))
        {
            fail_with_msg("class not declared: " + current_visiting_class);
        }
        // fail_with_msg("-----------immutable class decleared!-----------" + current_visiting_class);
    }

    if (node->vdl != nullptr) {
        for (auto vd : *(node->vdl)) {
            if (vd != nullptr) {
                vd->accept(*this);
            }
        }
    }
    if (node->mdl != nullptr) {
        for (auto md : *(node->mdl)) {
            if (md != nullptr) {
                md->accept(*this);
            }
        }
    }

    current_visiting_class = "";
}

void AST_Name_Map_Visitor::visit(MainMethod* node) {
    if (node == nullptr) {
        return;
    }

    if (!name_maps->add_class(kMainClassName)) {
        fail_with_msg("duplicate synthetic main class", node);
    }
    if (!name_maps->add_method(kMainClassName, kMainMethodName)) {
        fail_with_msg("duplicate main method", node);
    }

    current_visiting_class = kMainClassName;
    current_visiting_method = kMainMethodName;

    if (node->vdl != nullptr) {
        for (auto vd : *(node->vdl)) {
            if (vd != nullptr) {
                vd->accept(*this);
            }
        }
    }
    if (node->sl != nullptr) {
        for (auto stm : *(node->sl)) {
            if (stm != nullptr) {
                stm->accept(*this);
            }
        }
    }

    // Main method has implicit int return type.
    Type* main_ret_type = new Type(node->getPos() != nullptr ? node->getPos()->clone() : new Pos(0, 0, 0, 0));
    Formal* ret_formal = make_return_formal(node, main_ret_type);
    if (!name_maps->add_method_formal(current_visiting_class, current_visiting_method, kReturnFormalName, ret_formal)) {
        fail_with_msg("failed to record main return type", node);
    }
    vector<string> formals_with_return;
    formals_with_return.push_back(kReturnFormalName);
    if (!name_maps->add_method_formal_list(current_visiting_class, current_visiting_method, formals_with_return)) {
        fail_with_msg("failed to record main formal list", node);
    }

    current_visiting_method = "";
    current_visiting_class = "";
}//formal_list: vector<string>; method formal:(string,string,string)->Formal*

void AST_Name_Map_Visitor::visit(Type* node) {
    if (node == nullptr) {
        return;
    }
    if (node->typeKind == TypeKind::CLASS) {
        if (node->cid == nullptr || !name_maps->is_class(node->cid->id)) {
            fail_with_msg("unknown class type in declaration", node);
        }
    }
}

void AST_Name_Map_Visitor::visit(VarDecl* node) {
    if (node == nullptr || node->id == nullptr || node->type == nullptr) {
        return;
    }

    node->type->accept(*this);

    const string& name = node->id->id;
    if (current_visiting_method.empty()) {
        if (current_visiting_class.empty()) {
            fail_with_msg("variable declaration outside class/method scope", node);
        }
        if (!name_maps->add_class_var(current_visiting_class, name, node)) {
            fail_with_msg("duplicate class variable: " + current_visiting_class + "::" + name, node->id);
        }
        return;
    }

    // Keep formals in signature maps; local vars shadow them during lookup.
    if (!name_maps->add_method_var(current_visiting_class, current_visiting_method, name, node)) {
        fail_with_msg("duplicate local variable: " + current_visiting_class + "::" + current_visiting_method + "::" + name, node->id);
    }
}

void AST_Name_Map_Visitor::visit(MethodDecl* node) {
    if (node == nullptr || node->id == nullptr || node->type == nullptr) {
        return;
    }
    if (current_visiting_class.empty()) {
        fail_with_msg("method declaration outside class scope", node);
    }

    const string method_name = node->id->id;
    if (!name_maps->add_method(current_visiting_class, method_name)) {
        fail_with_msg("duplicate method declaration: " + current_visiting_class + "::" + method_name, node->id);
    }

    current_visiting_method = method_name;
    node->type->accept(*this);

    vector<string> formal_names;
    if (node->fl != nullptr) {
        for (auto f : *(node->fl)) {
            if (f == nullptr || f->id == nullptr) {
                continue;
            }
            formal_names.push_back(f->id->id);
            f->accept(*this);
        }
    }

    Formal* ret_formal = make_return_formal(node, node->type);
    if (!name_maps->add_method_formal(current_visiting_class, current_visiting_method, kReturnFormalName, ret_formal)) {
        fail_with_msg("failed to record method return type: " + method_name, node);
    }
    formal_names.push_back(kReturnFormalName);
    if (!name_maps->add_method_formal_list(current_visiting_class, current_visiting_method, formal_names)) {
        fail_with_msg("failed to record method formal list: " + method_name, node);
    }

    if (node->vdl != nullptr) {
        for (auto vd : *(node->vdl)) {
            if (vd != nullptr) {
                vd->accept(*this);
            }
        }
    }
    if (node->sl != nullptr) {
        for (auto stm : *(node->sl)) {
            if (stm != nullptr) {
                stm->accept(*this);
            }
        }
    }

    current_visiting_method = "";
}

void AST_Name_Map_Visitor::visit(Formal* node) {
    if (node == nullptr || node->id == nullptr || node->type == nullptr) {
        return;
    }
    if (current_visiting_class.empty() || current_visiting_method.empty()) {
        fail_with_msg("formal parameter outside method scope", node);
    }

    node->type->accept(*this);

    const string& formal_name = node->id->id;
    if (!name_maps->add_method_formal(current_visiting_class, current_visiting_method, formal_name, node)) {
        fail_with_msg("duplicate formal parameter: " + current_visiting_class + "::" + current_visiting_method + "::" + formal_name, node->id);
    }
}

void AST_Name_Map_Visitor::visit(Nested* node) {
    if (node == nullptr || node->sl == nullptr) {
        return;
    }
    for (auto stm : *(node->sl)) {
        if (stm != nullptr) {
            stm->accept(*this);
        }
    }
}

void AST_Name_Map_Visitor::visit(If* node) {
    if (node == nullptr) {
        return;
    }
    if (node->exp != nullptr) {
        node->exp->accept(*this);
    }
    if (node->stm1 != nullptr) {
        node->stm1->accept(*this);
    }
    if (node->stm2 != nullptr) {
        node->stm2->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(While* node) {
    if (node == nullptr) {
        return;
    }
    if (node->exp != nullptr) {
        node->exp->accept(*this);
    }
    if (node->stm != nullptr) {
        node->stm->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(Assign* node) {
    if (node == nullptr) {
        return;
    }
    if (node->left != nullptr) {
        node->left->accept(*this);
    }
    if (node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(CallStm* node) {
    if (node == nullptr) {
        return;
    }
    if (node->obj != nullptr) {
        node->obj->accept(*this);
    }
    if (node->name != nullptr) {
        node->name->accept(*this);
    }
    if (node->par != nullptr) {
        for (auto p : *(node->par)) {
            if (p != nullptr) {
                p->accept(*this);
            }
        }
    }
}

void AST_Name_Map_Visitor::visit(Continue* node) { (void)node; }
void AST_Name_Map_Visitor::visit(Break* node) { (void)node; }

void AST_Name_Map_Visitor::visit(Return* node) {
    if (node != nullptr && node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(PutInt* node) {
    if (node != nullptr && node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(PutCh* node) {
    if (node != nullptr && node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(PutArray* node) {
    if (node == nullptr) {
        return;
    }
    if (node->n != nullptr) {
        node->n->accept(*this);
    }
    if (node->arr != nullptr) {
        node->arr->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(Starttime* node) { (void)node; }
void AST_Name_Map_Visitor::visit(Stoptime* node) { (void)node; }

void AST_Name_Map_Visitor::visit(BinaryOp* node) {
    if (node == nullptr) {
        return;
    }
    if (node->left != nullptr) {
        node->left->accept(*this);
    }
    if (node->op != nullptr) {
        node->op->accept(*this);
    }
    if (node->right != nullptr) {
        node->right->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(UnaryOp* node) {
    if (node == nullptr) {
        return;
    }
    if (node->op != nullptr) {
        node->op->accept(*this);
    }
    if (node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(ArrayExp* node) {
    if (node == nullptr) {
        return;
    }
    if (node->arr != nullptr) {
        node->arr->accept(*this);
    }
    if (node->index != nullptr) {
        node->index->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(CallExp* node) {
    if (node == nullptr) {
        return;
    }
    if (node->obj != nullptr) {
        node->obj->accept(*this);
    }
    if (node->name != nullptr) {
        node->name->accept(*this);
    }
    if (node->par != nullptr) {
        for (auto p : *(node->par)) {
            if (p != nullptr) {
                p->accept(*this);
            }
        }
    }
}

void AST_Name_Map_Visitor::visit(ClassVar* node) {
    if (node == nullptr) {
        return;
    }
    if (node->obj != nullptr) {
        node->obj->accept(*this);
    }
    if (node->id != nullptr) {
        node->id->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(This* node) { (void)node; }

void AST_Name_Map_Visitor::visit(Length* node) {
    if (node != nullptr && node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(NewArray* node) {
    if (node != nullptr && node->size != nullptr) {
        node->size->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(NewObject* node) {
    if (node != nullptr && node->id != nullptr) {
        node->id->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(GetInt* node) { (void)node; }
void AST_Name_Map_Visitor::visit(GetCh* node) { (void)node; }

void AST_Name_Map_Visitor::visit(GetArray* node) {
    if (node != nullptr && node->exp != nullptr) {
        node->exp->accept(*this);
    }
}

void AST_Name_Map_Visitor::visit(IdExp* node) { (void)node; }
void AST_Name_Map_Visitor::visit(OpExp* node) { (void)node; }
void AST_Name_Map_Visitor::visit(IntExp* node) { (void)node; }
